album:
    type:     rest
    resource: GalerijaREST\ApiBundle\Controller\AlbumController
    defaults: {_format: json}
images:
    type:         rest
    resource:     GalerijaREST\ApiBundle\Controller\ImageController

comments:
    type:         rest
    resource:     GalerijaREST\ApiBundle\Controller\CommentController
tags:
    type:         rest
    resource:     GalerijaREST\ApiBundle\Controller\TagController
